name: App
include:
  - app/addons/addons.yml
packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
  WebRTC:
    url: https://github.com/stasel/WebRTC
    branch: release-M137
  BareRPC:
    url: https://github.com/holepunchto/bare-rpc-swift
    branch: main
targets:
  App:
    type: application
    supportedDestinations: [macOS]
    deploymentTarget:
      iOS: 18.4
      macOS: 15.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0

      configs:
        Debug:
          CODE_SIGN_IDENTITY: '-'
          CODE_SIGN_STYLE: Manual
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
          VALIDATE_PRODUCT: NO
          VALIDATE_WORKSPACE: NO
          OTHER_CODE_SIGN_FLAGS: '--deep --no-strict'
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: 'Apple Development'
          CODE_SIGNING_REQUIRED: YES
          VALIDATE_PRODUCT: YES
    info:
      path: app/Info.plist
    entitlements:
      path: app/App.entitlements
      properties:
        com.apple.security.cs.allow-jit: true
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
      - package: WebRTC
        product: WebRTC
      - package: BareRPC
    sources:
      - path: app/App.swift
      - path: app/app.bundle
        optional: true

      - path: app/js/app.js
        group: app/js
      - path: app/js/capture.js
      - path: app/js/peers.js
      - path: app/js/protocol.js
      - path: app/js/rpc.js
      - path: app/js/swarm.js

      - path: app/RPC/MediaProtocol.swift
        group: app/RPC
      - path: app/RPC/RPCBridge.swift
      - path: app/RPC/RPCTransport.swift

      - path: app/Views/LobbyView.swift
        group: app/Views
      - path: app/Views/VideoCallView.swift

      - path: app/ViewModel/CallViewModel.swift
        group: app/ViewModel

      - path: app/Media/AudioRenderer.swift
        group: app/Media
      - path: app/Media/MediaRenderer.swift
      - path: app/Media/VideoSurface.swift

    scheme:
      preActions:
        - name: Link & Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --out ${PWD}/app/addons/ \
              ${PWD}

            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/js/app.js
