name: App
include:
  - app/addons/addons.yml
packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
  WebRTC:
    url: https://github.com/stasel/WebRTC
    branch: release-M137
targets:
  App:
    type: application
    supportedDestinations: [macOS]
    deploymentTarget:
      iOS: 18.4
      macOS: 15.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0

      configs:
        Debug:
          CODE_SIGN_IDENTITY: '-'
          CODE_SIGN_STYLE: Manual
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
          VALIDATE_PRODUCT: NO
          VALIDATE_WORKSPACE: NO
          OTHER_CODE_SIGN_FLAGS: '--deep --no-strict'
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: 'Apple Development'
          CODE_SIGNING_REQUIRED: YES
          VALIDATE_PRODUCT: YES
    info:
      path: app/Info.plist
    entitlements:
      path: app/App.entitlements
      properties:
        com.apple.security.cs.allow-jit: true
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
      - package: WebRTC
        product: WebRTC
    sources:
      - path: app/App.swift
      - path: app/app.bundle
        optional: true

      - path: app/js/app.js
        group: app/js

      - path: app/Core/Domain/WebRTCManager.swift
        group: app/Core/Domain
      - path: app/Core/Domain/PeerSession.swift

      - path: app/Core/Helper/CallState.swift
        group: app/Core/Helper

      - path: app/Core/IPC/BareKitBridge.swift
        group: app/Core/IPC
      - path: app/Core/IPC/Worker.swift

      - path: app/Core/Home/View/LobbyView.swift
        group: app/Core/Home/View
      - path: app/Core/Home/View/VideoCallView.swift

      - path: app/Core/Home/ViewModel/CallViewModel.swift
        group: app/Core/Home/ViewModel

      - path: app/Core/Root/AppRouter.swift
        group: app/Core/Root
      - path: app/Core/Root/RootView.swift

        optional: true
    scheme:
      preActions:
        - name: Link & Pack
          script: |
            
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --out ${PWD}/addons/ \
              ${PWD}
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app.bundle \
              ${PWD}/app/js/app.js


